### ISSUE TITLE
Change configuration via web UI

### ISSUE THREAD

**Issue by vyruz1986** [vyruz1986/FlyballSensor#16]
It should be possible to modify the system configuration via the web UI:
* Set password for WiFi AP (and f/w upload?)
* Modify WiFi AP name

The initial version of this configuration UI should implement a framework which allows us to easily add additional configuration parameters in the future

**Comment by simonttp78** [comment]
Isn't this implemented already?

**Comment by vyruz1986** [comment]
I did add a couple of things, yes, but it doesn't really work right now. Don't remember the exact state of things, but I do remember it wasn't really on a usable level.

**Comment by simonttp78** [comment]
I've checked the code and it was almost ready, but inactive. Just added solution for reading config data and it's working. I made pull request for this.

**Comment by vyruz1986** [comment]
Awesome, thanks @simonttp78 !
